---
deployment:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build:prod
  displayName: 'npm install and build'
  
- export DEPLOYPATH=/home/stemrecr/stem_app/
    - /backend/dist server.js $DEPLOYPATH
    - /frontend/dist index.html $DEPLOYPATH
